//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellEmulatorMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        public Well()
        {
            this.WellTests = new HashSet<WellTest>();
        }
    
        public int idWell { get; set; }
        public string nameWell { get; set; }
        public Nullable<int> idTypeWell { get; set; }
        public Nullable<int> idOilfield { get; set; }
        public string nameLegal { get; set; }
        public string numLicense { get; set; }
        public string numGovt { get; set; }
        public Nullable<System.DateTime> dTimLicense { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string block { get; set; }
        public string timeZone { get; set; }
        public string @operator { get; set; }
        public string operatorDiv { get; set; }
        public Nullable<double> pcInterest { get; set; }
        public string numAPI { get; set; }
        public Nullable<int> idStatusWell { get; set; }
        public string purposeWell { get; set; }
        public Nullable<System.DateTime> dTimSpud { get; set; }
        public Nullable<System.DateTime> dTimPa { get; set; }
        public Nullable<double> wellheadElevation { get; set; }
        public Nullable<double> groundElevation { get; set; }
        public Nullable<double> waterDepth { get; set; }
    
        public virtual ICollection<WellTest> WellTests { get; set; }
    }
}
