//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellEmulatorMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PdgtmDb : DbContext
    {
        public PdgtmDb()
            : base("name=PdgtmDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProductionTest> ProductionTests { get; set; }
        public DbSet<ProductionTestResult> ProductionTestResults { get; set; }
        public DbSet<Well> Wells { get; set; }
        public DbSet<WellTest> WellTests { get; set; }
    }
}
