//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellEmulatorMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTestResult
    {
        public int idProductionTestResults { get; set; }
        public Nullable<int> idProductionTest { get; set; }
        public Nullable<double> oilRate { get; set; }
        public Nullable<double> gasRate { get; set; }
        public Nullable<double> waterRate { get; set; }
    
        public virtual ProductionTest ProductionTest { get; set; }
    }
}
