//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellEmulatorMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTest
    {
        public ProductionTest()
        {
            this.ProductionTestResults = new HashSet<ProductionTestResult>();
        }
    
        public int idProductionTest { get; set; }
        public Nullable<int> idWellTest { get; set; }
        public Nullable<int> productionTest1 { get; set; }
    
        public virtual WellTest WellTest { get; set; }
        public virtual ICollection<ProductionTestResult> ProductionTestResults { get; set; }
    }
}
