//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellEmulatorClient.WellEmulatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WellEmulator.com", ConfigurationName="WellEmulatorServiceReference.IWellEmulator")]
    public interface IWellEmulator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WellEmulator.com/IWellEmulator/MethodForTest", ReplyAction="http://WellEmulator.com/IWellEmulator/MethodForTestResponse")]
        string MethodForTest(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WellEmulator.com/IWellEmulator/MethodForTest", ReplyAction="http://WellEmulator.com/IWellEmulator/MethodForTestResponse")]
        System.Threading.Tasks.Task<string> MethodForTestAsync(string request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWellEmulatorChannel : WellEmulatorClient.WellEmulatorServiceReference.IWellEmulator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WellEmulatorClient : System.ServiceModel.ClientBase<WellEmulatorClient.WellEmulatorServiceReference.IWellEmulator>, WellEmulatorClient.WellEmulatorServiceReference.IWellEmulator {
        
        public WellEmulatorClient() {
        }
        
        public WellEmulatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WellEmulatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellEmulatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellEmulatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MethodForTest(string request) {
            return base.Channel.MethodForTest(request);
        }
        
        public System.Threading.Tasks.Task<string> MethodForTestAsync(string request) {
            return base.Channel.MethodForTestAsync(request);
        }
    }
}
